#!/usr/bin/env bash

set -e
# get dotfiles dir
DOTFILES_BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# dotfiles that will get linked from $HOME
DOTFILES=(bashrc inputrc ackrc gitconfig)

# create backups of existing files
function backup_existing {
    mkdir -p $HOME/.dotfiles_backup

    for file in "${DOTFILES[@]}"
    do
        # remove existing links
        if [ -h "$HOME/.$file" ]; then
            rm "$HOME/.$file"
        fi
        # move existing files to backup dir
        if [ -f "$HOME/.$file" ]; then
            mv "$HOME/.$file" "$HOME/.dotfiles_backup/" --backup
        fi
    done
}

# install links
function install {
    echo "export DOTFILES_HOME=\"$DOTFILES_BASEDIR\"" > $HOME/.bashrc.dotfiles
    for file in "${DOTFILES[@]}"
    do
        ln -s "$DOTFILES_BASEDIR/$file" "$HOME/.$file"
    done
}

backup_existing
install
